apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulletin-board
  template:
    metadata:
      labels:
        app: bulletin-board
    spec:
      containers:
        - name: bulletin-board
          image: rcandra612/bulletin-board:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: ${{ secrets.SPRING_DATASOURCE_URL }}
            - name: SPRING_DATASOURCE_USERNAME
              value: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ${{ secrets.POSTGRES_DB }}
            - name: POSTGRES_USER
              value: ${{ secrets.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: ${{ secrets.POSTGRES_PASSWORD }}

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: bulletin-board
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
